# Regras de associação

In [ ]:
# Instalar no python o 'mlxtend'

pip install mlxtend

In [1]:
# Bibliotecas e funções

import pandas as pd 
from mlxtend.preprocessing import TransactionEncoder # Utilizada para tratar e deixar os dados pronta p/ utilizar com o apriore
from mlxtend.frequent_patterns import apriori # Função para extrair conjuntos de itens frequentes.
from mlxtend.frequent_patterns import association_rules 

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)
pd.set_option('precision', 2)

In [2]:
# DataSet 

dataset = [
    ['Leite', 'Cebola', 'Batata', 'Feijão', 'Ovos', 'Iogurte'],
    ['Arroz', 'Cebola', 'Batata', 'Feijão', 'Ovos', 'Iogurte'],
    ['Leite', 'Maçã', 'Feijão', 'Ovos'],
    ['Leite', 'Milho', 'Feijão', 'Iogurte'],
    ['Milho', 'Cebola', 'Feijão', 'Sorvete', 'Ovos']
]

In [3]:
to = TransactionEncoder() # Váriavel vai receber a função para tratamento dos dados.
to_ary = to.fit(dataset).transform(dataset) #Transformação dos dados
df = pd.DataFrame(to_ary, columns=to.columns_) # Converter a 'to_ary' no DataFrame
frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True) # 3 dos 5 registro tem que possuir um alimento para ser 
# considerado frequente. 

print(frequent_itemsets)

    support                itemsets
0       0.6                (Cebola)
1       1.0                (Feijão)
2       0.6               (Iogurte)
3       0.6                 (Leite)
4       0.8                  (Ovos)
5       0.6        (Cebola, Feijão)
6       0.6          (Ovos, Cebola)
7       0.6       (Feijão, Iogurte)
8       0.6         (Feijão, Leite)
9       0.8          (Ovos, Feijão)
10      0.6  (Ovos, Cebola, Feijão)

### Regras de associação

In [4]:
# função 'association_rules' para a confiança da regra. 

association_rules(frequent_itemsets, metric='confidence', min_threshold=0.7)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Cebola),(Feijão),0.6,1.0,0.6,1.00,1.00,0.00,inf
1,(Ovos),(Cebola),0.8,0.6,0.6,0.75,1.25,0.12,1.6
2,(Cebola),(Ovos),0.6,0.8,0.6,1.00,1.25,0.12,inf
3,(Iogurte),(Feijão),0.6,1.0,0.6,1.00,1.00,0.00,inf
4,(Leite),(Feijão),0.6,1.0,0.6,1.00,1.00,0.00,inf
5,(Ovos),(Feijão),0.8,1.0,0.8,1.00,1.00,0.00,inf
6,(Feijão),(Ovos),1.0,0.8,0.8,0.80,1.00,0.00,1.0
7,"(Ovos, Cebola)",(Feijão),0.6,1.0,0.6,1.00,1.00,0.00,inf
8,"(Ovos, Feijão)",(Cebola),0.8,0.6,0.6,0.75,1.25,0.12,1.6
9,"(Cebola, Feijão)",(Ovos),0.6,0.8,0.6,1.00,1.25,0.12,inf
10,(Ovos),"(Cebola, Feijão)",0.8,0.6,0.6,0.75,1.25,0.12,1.6
11,(Cebola),"(Ovos, Feijão)",0.6,0.8,0.6,1.00,1.25,0.12,inf

In [5]:
# Gerar regra de associação para o 'lift' minimo de 1.2
# Valores de lift inferior a 1 significa que a regra não possui causalidade relevante e não aumentam o nosso poder de previsão.

rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1.2)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Ovos),(Cebola),0.8,0.6,0.6,0.75,1.25,0.12,1.6
1,(Cebola),(Ovos),0.6,0.8,0.6,1.00,1.25,0.12,inf
2,"(Ovos, Feijão)",(Cebola),0.8,0.6,0.6,0.75,1.25,0.12,1.6
3,"(Cebola, Feijão)",(Ovos),0.6,0.8,0.6,1.00,1.25,0.12,inf
4,(Ovos),"(Cebola, Feijão)",0.8,0.6,0.6,0.75,1.25,0.12,1.6
5,(Cebola),"(Ovos, Feijão)",0.6,0.8,0.6,1.00,1.25,0.12,inf

In [6]:
# Lambda utilizado para identificar o cumprimento do 'antecedents'. É importante o envio da 'frequent_itemsets' para a variável
# porque será feito o tratamento necessário.

rules['antecedent_len'] = rules ['antecedents'].apply(lambda x:len(x)) 
print(rules)

        antecedents       consequents  antecedent support  consequent support  \
0            (Ovos)          (Cebola)                 0.8                 0.6
1          (Cebola)            (Ovos)                 0.6                 0.8
2    (Ovos, Feijão)          (Cebola)                 0.8                 0.6
3  (Cebola, Feijão)            (Ovos)                 0.6                 0.8
4            (Ovos)  (Cebola, Feijão)                 0.8                 0.6
5          (Cebola)    (Ovos, Feijão)                 0.6                 0.8

   support  confidence  lift  leverage  conviction  antecedent_len
0      0.6        0.75  1.25      0.12         1.6               1
1      0.6        1.00  1.25      0.12         inf               1
2      0.6        0.75  1.25      0.12         1.6               2
3      0.6        1.00  1.25      0.12         inf               2
4      0.6        0.75  1.25      0.12         1.6               1
5      0.6        1.00  1.25      0.12         inf               1

In [7]:
# Slice (fatiamento) da variável 'rules'

rules [(rules['antecedent_len'] >= 2) & 
       (rules['confidence'] > 0.75) & 
       (rules['lift'] > 1.2)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
3,"(Cebola, Feijão)",(Ovos),0.6,0.8,0.6,1.0,1.25,0.12,inf,2

In [8]:
# Altera a coluna 'antecedents'. 

rules [rules['antecedents']== {'Ovos', 'Feijão'}]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
2,"(Ovos, Feijão)",(Cebola),0.8,0.6,0.6,0.75,1.25,0.12,1.6,2

### Amálise de cesta de compras em Python

In [1]:
# Bibliotecas

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [4]:
df = pd.read_excel('E:\PUC-MG\Machine learning\Online_Retail.xlsx')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [5]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [8]:
df['Description'] = df['Description'].str.strip() # Remove o espaço do inicio ao fim da string 
df.dropna(axis=0, subset=['InvoiceNo'], inplace=True) # Remove campos com informações faltantes 
df['InvoiceNo'] = df['InvoiceNo'].astype('str')
df = df[~df['InvoiceNo'].str.contains('C')] # Remove os pedidos que começam com a letra 'C'
df.describe()

            Quantity      UnitPrice     CustomerID
count  532621.000000  532621.000000  397924.000000
mean       10.239972       3.847621   15294.315171
std       159.593551      41.758023    1713.169877
min     -9600.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13969.000000
50%         3.000000       2.080000   15159.000000
75%        10.000000       4.130000   16795.000000
max     80995.000000   13541.330000   18287.000000

In [29]:
basket = (df[df['Country'] == 'France']
          .groupby(['InvoiceNo', 'Description']) ['Quantity']
          .sum().unstack().reset_index().fillna(0)
          .set_index('InvoiceNo'))
basket.head()

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536852,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536974,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537065,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
537463,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
def encode_units (x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1
basket_sets = basket.applymap(encode_units)
basket_sets.drop('POSTAGE', inplace=True, axis=1)

basket_sets.head()

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536370,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536852,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536974,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
537463,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
basket_sets.describe()

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 EGG HOUSE PAINTED WOOD,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE WOODLAND,...,WRAP VINTAGE PETALS DESIGN,YELLOW COAT RACK PARIS FASHION,YELLOW GIANT GARDEN THERMOMETER,YELLOW SHARK HELICOPTER,ZINC STAR T-LIGHT HOLDER,ZINC FOLKART SLEIGH BELLS,ZINC HERB GARDEN CONTAINER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL
count,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,...,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000,392.000000
mean,0.030612,0.015306,0.002551,0.005102,0.015306,0.017857,0.017857,0.002551,0.022959,0.015306,...,0.007653,0.005102,0.002551,0.002551,0.002551,0.017857,0.002551,0.010204,0.002551,0.005102
std,0.172485,0.122924,0.050508,0.071337,0.122924,0.132601,0.132601,0.050508,0.149965,0.122924,...,0.087258,0.071337,0.050508,0.050508,0.050508,0.132601,0.050508,0.100627,0.050508,0.071337
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [15]:
# Gerando frequentes da regra de associação. 

frequent_itemsets = apriori(basket_sets, min_support=0.07, use_colnames=True)
frequent_itemsets

rules = association_rules(frequent_itemsets, metric = 'lift', min_threshold=1)
print('\nAlgumas regras de associação geradas: \n', rules.head())
print('\n Dimensões da matriz de regras:\n', rules.shape)

Algumas regras de associação geradas:
                     antecedents                   consequents  \
0  (ALARM CLOCK BAKELIKE GREEN)   (ALARM CLOCK BAKELIKE PINK)
1   (ALARM CLOCK BAKELIKE PINK)  (ALARM CLOCK BAKELIKE GREEN)
2    (ALARM CLOCK BAKELIKE RED)  (ALARM CLOCK BAKELIKE GREEN)
3  (ALARM CLOCK BAKELIKE GREEN)    (ALARM CLOCK BAKELIKE RED)
4    (ALARM CLOCK BAKELIKE RED)   (ALARM CLOCK BAKELIKE PINK)

   antecedent support  consequent support   support  confidence      lift  \
0            0.096939            0.102041  0.073980    0.763158  7.478947
1            0.102041            0.096939  0.073980    0.725000  7.478947
2            0.094388            0.096939  0.079082    0.837838  8.642959
3            0.096939            0.094388  0.079082    0.815789  8.642959
4            0.094388            0.102041  0.073980    0.783784  7.681081

   leverage  conviction
0  0.064088    3.791383
1  0.064088    3.283859
2  0.069932    5.568878
3  0.069932    4.916181
4  0.064348    4.153061

 Dimensões da matriz de regras:
 (26, 9)

## Exemplos de filtros sobre regras de associação

In [16]:
rules[ (rules ['lift'] >= 6 ) &
       (rules['confidence'] >= 0.8)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
2,(ALARM CLOCK BAKELIKE RED),(ALARM CLOCK BAKELIKE GREEN),0.094388,0.096939,0.079082,0.837838,8.642959,0.069932,5.568878
3,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED),0.096939,0.094388,0.079082,0.815789,8.642959,0.069932,4.916181
17,(SET/6 RED SPOTTY PAPER PLATES),(SET/20 RED RETROSPOT PAPER NAPKINS),0.127551,0.132653,0.102041,0.800000,6.030769,0.085121,4.336735
18,(SET/6 RED SPOTTY PAPER CUPS),(SET/6 RED SPOTTY PAPER PLATES),0.137755,0.127551,0.122449,0.888889,6.968889,0.104878,7.852041
19,(SET/6 RED SPOTTY PAPER PLATES),(SET/6 RED SPOTTY PAPER CUPS),0.127551,0.137755,0.122449,0.960000,6.968889,0.104878,21.556122
20,"(SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...",(SET/6 RED SPOTTY PAPER PLATES),0.102041,0.127551,0.099490,0.975000,7.644000,0.086474,34.897959
21,"(SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...",(SET/6 RED SPOTTY PAPER CUPS),0.102041,0.137755,0.099490,0.975000,7.077778,0.085433,34.489796
22,"(SET/6 RED SPOTTY PAPER CUPS, SET/6 RED SPOTTY...",(SET/20 RED RETROSPOT PAPER NAPKINS),0.122449,0.132653,0.099490,0.812500,6.125000,0.083247,4.625850

In [22]:
basket['ALARM CLOCK BAKELIKE GREEN'].sum()

340.0

In [23]:
basket['ALARM CLOCK BAKELIKE RED'].sum()

316.0

### Análise de compras da Alemanha

In [30]:
basket2 = (df[df['Country'] == 'Germany']
          .groupby(['InvoiceNo', 'Description']) ['Quantity']
          .sum().unstack().reset_index().fillna(0)
          .set_index('InvoiceNo'))
basket2.head()

Description,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 IVORY ROSE PEG PLACE SETTINGS,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,12 PENCILS SMALL TUBE RED RETROSPOT,12 PENCILS SMALL TUBE SKULL,12 PENCILS TALL TUBE POSY,12 PENCILS TALL TUBE RED RETROSPOT,12 PENCILS TALL TUBE SKULLS,...,YULETIDE IMAGES GIFT WRAP SET,ZINC HEART T-LIGHT HOLDER,ZINC STAR T-LIGHT HOLDER,ZINC BOX SIGN HOME,ZINC FOLKART SLEIGH BELLS,ZINC HEART LATTICE T-LIGHT HOLDER,ZINC METAL HEART DECORATION,ZINC T-LIGHT HOLDER STAR LARGE,ZINC T-LIGHT HOLDER STARS SMALL,ZINC WILLIE WINKIE CANDLE STICK
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536527,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536840,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536861,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536967,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536983,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
df['Country'].unique()

array(['United Kingdom', 'France', 'Australia', 'Netherlands', 'Germany',
       'Norway', 'EIRE', 'Switzerland', 'Spain', 'Poland', 'Portugal',
       'Italy', 'Belgium', 'Lithuania', 'Japan', 'Iceland',
       'Channel Islands', 'Denmark', 'Cyprus', 'Sweden', 'Finland',
       'Austria', 'Bahrain', 'Israel', 'Greece', 'Hong Kong', 'Singapore',
       'Lebanon', 'United Arab Emirates', 'Saudi Arabia',
       'Czech Republic', 'Canada', 'Unspecified', 'Brazil', 'USA',
       'European Community', 'Malta', 'RSA'], dtype=object)

In [35]:
basket_sets2 = basket2.applymap(encode_units)
basket_sets2.drop('POSTAGE', inplace=True, axis=1)
frequent_itemsets2 = apriori(basket_sets2,min_support=0.07, use_colnames=True)
frequent_itemsets2

rules2 = association_rules(frequent_itemsets2, metric = 'lift', min_threshold=1)
print('\nAlgumas regras de associação geradas: \n', rules2.head())
print('\n Dimensões da matriz de regras:\n', rules2.shape)
rules[ (rules ['lift'] >= 4 ) &
       (rules['confidence'] >= 0.5)]

Algumas regras de associação geradas:
                             antecedents                           consequents  \
0  (ROUND SNACK BOXES SET OF4 WOODLAND)    (PLASTERS IN TIN WOODLAND ANIMALS)
1    (PLASTERS IN TIN WOODLAND ANIMALS)  (ROUND SNACK BOXES SET OF4 WOODLAND)
2   (ROUND SNACK BOXES SET OF 4 FRUITS)  (ROUND SNACK BOXES SET OF4 WOODLAND)
3  (ROUND SNACK BOXES SET OF4 WOODLAND)   (ROUND SNACK BOXES SET OF 4 FRUITS)
4                  (SPACEBOY LUNCH BOX)  (ROUND SNACK BOXES SET OF4 WOODLAND)

   antecedent support  consequent support   support  confidence      lift  \
0            0.245077            0.137856  0.074398    0.303571  2.202098
1            0.137856            0.245077  0.074398    0.539683  2.202098
2            0.157549            0.245077  0.131291    0.833333  3.400298
3            0.245077            0.157549  0.131291    0.535714  3.400298
4            0.102845            0.245077  0.070022    0.680851  2.778116

   leverage  conviction
0  0.040613    1.237951
1  0.040613    1.640006
2  0.092679    4.529540
3  0.092679    1.814509
4  0.044817    2.365427

 Dimensões da matriz de regras:
 (6, 9)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE PINK),0.096939,0.102041,0.073980,0.763158,7.478947,0.064088,3.791383
1,(ALARM CLOCK BAKELIKE PINK),(ALARM CLOCK BAKELIKE GREEN),0.102041,0.096939,0.073980,0.725000,7.478947,0.064088,3.283859
2,(ALARM CLOCK BAKELIKE RED),(ALARM CLOCK BAKELIKE GREEN),0.094388,0.096939,0.079082,0.837838,8.642959,0.069932,5.568878
3,(ALARM CLOCK BAKELIKE GREEN),(ALARM CLOCK BAKELIKE RED),0.096939,0.094388,0.079082,0.815789,8.642959,0.069932,4.916181
4,(ALARM CLOCK BAKELIKE RED),(ALARM CLOCK BAKELIKE PINK),0.094388,0.102041,0.073980,0.783784,7.681081,0.064348,4.153061
5,(ALARM CLOCK BAKELIKE PINK),(ALARM CLOCK BAKELIKE RED),0.102041,0.094388,0.073980,0.725000,7.681081,0.064348,3.293135
6,(SPACEBOY LUNCH BOX),(DOLLY GIRL LUNCH BOX),0.125000,0.099490,0.071429,0.571429,5.743590,0.058992,2.101190
7,(DOLLY GIRL LUNCH BOX),(SPACEBOY LUNCH BOX),0.099490,0.125000,0.071429,0.717949,5.743590,0.058992,3.102273
12,(PLASTERS IN TIN SPACEBOY),(PLASTERS IN TIN WOODLAND ANIMALS),0.137755,0.170918,0.104592,0.759259,4.442233,0.081047,3.443878
13,(PLASTERS IN TIN WOODLAND ANIMALS),(PLASTERS IN TIN SPACEBOY),0.170918,0.137755,0.104592,0.611940,4.442233,0.081047,2.221939
14,(SET/20 RED RETROSPOT PAPER NAPKINS),(SET/6 RED SPOTTY PAPER CUPS),0.132653,0.137755,0.102041,0.769231,5.584046,0.083767,3.736395
15,(SET/6 RED SPOTTY PAPER CUPS),(SET/20 RED RETROSPOT PAPER NAPKINS),0.137755,0.132653,0.102041,0.740741,5.584046,0.083767,3.345481
16,(SET/20 RED RETROSPOT PAPER NAPKINS),(SET/6 RED SPOTTY PAPER PLATES),0.132653,0.127551,0.102041,0.769231,6.030769,0.085121,3.780612
17,(SET/6 RED SPOTTY PAPER PLATES),(SET/20 RED RETROSPOT PAPER NAPKINS),0.127551,0.132653,0.102041,0.800000,6.030769,0.085121,4.336735
18,(SET/6 RED SPOTTY PAPER CUPS),(SET/6 RED SPOTTY PAPER PLATES),0.137755,0.127551,0.122449,0.888889,6.968889,0.104878,7.852041
19,(SET/6 RED SPOTTY PAPER PLATES),(SET/6 RED SPOTTY PAPER CUPS),0.127551,0.137755,0.122449,0.960000,6.968889,0.104878,21.556122
20,"(SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...",(SET/6 RED SPOTTY PAPER PLATES),0.102041,0.127551,0.099490,0.975000,7.644000,0.086474,34.897959
21,"(SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...",(SET/6 RED SPOTTY PAPER CUPS),0.102041,0.137755,0.099490,0.975000,7.077778,0.085433,34.489796
22,"(SET/6 RED SPOTTY PAPER CUPS, SET/6 RED SPOTTY...",(SET/20 RED RETROSPOT PAPER NAPKINS),0.122449,0.132653,0.099490,0.812500,6.125000,0.083247,4.625850
23,(SET/20 RED RETROSPOT PAPER NAPKINS),"(SET/6 RED SPOTTY PAPER CUPS, SET/6 RED SPOTTY...",0.132653,0.122449,0.099490,0.750000,6.125000,0.083247,3.510204
24,(SET/6 RED SPOTTY PAPER CUPS),"(SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...",0.137755,0.102041,0.099490,0.722222,7.077778,0.085433,3.232653
25,(SET/6 RED SPOTTY PAPER PLATES),"(SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...",0.127551,0.102041,0.099490,0.780000,7.644000,0.086474,4.081633